
name: build-prod
on:
  workflow_run:
    workflows: [Test and Lint]
    branches: [main]
    types:
      - completed
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker
        run: docker login rg.fr-par.scw.cloud/picnicdouille -u nologin -p '${{ secrets.SCWTOKEN }}'
      - name: Build API Container
        run: |
          cd backend
          docker build -f Dockerfile --tag rg.fr-par.scw.cloud/picnicdouille/picnicdouille_app:${{ github.sha }} .
      - name: Push Container in registry
        run: docker push rg.fr-par.scw.cloud/picnicdouille/picnicdouille_app:${{ github.sha }}

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo "CPT MICHEL"

